### ISSUE TITLE
Working wrong with windows backslash

### ISSUE THREAD

**Issue by Yongjun042** [zoubingwu/vite-plugin-next-react-router#1]
```
import GlobalLayout from './pages\_layout'

const DynamicIndex = React.lazy(() => import('./pages\index'));
const DynamicIndex = React.lazy(() => import('./pages\products\index'));
const DynamicId = React.lazy(() => import('./pages\products\[id]'));
]
```

Like this it cannot handle backslash filepath.

**Comment by ipadorusa** [comment]
감사합니다.... 맥에서 하다가 윈도우에서 오류 생겨서 두시간 허비했는데 ㅎㅎ

**Comment by zoubingwu** [comment]
please upgrade to v0.7.1, there is breaking change but this should be fixed in https://github.com/zoubingwu/vite-plugin-next-react-router/commit/f422bb3bf42d60d517524031faaae2652cef28c1
