### ISSUE TITLE
`Outlet` is missing import in `routes.tsx`

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [zoubingwu/vite-plugin-next-react-router#3]
When `/src/routes.tsx` is generated it is missing import for <Outlet/> component.
`import { Outlet } from 'react-router-dom';`

Where `Outlet` is used in file (auto-generated) 
```
export const routes = [
  {
    path: '/',
    element: <Outlet />,
    children: [
      { path: '/', element: <DynamicIndex />, index: true},
      ...
      ]
  }
```

My `package.json`:
```
{
  "name": "react-vite-tailwind",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "start": "vite --port=3000",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@headlessui/react": "^1.6.6",
    "@headlessui/tailwindcss": "^0.1.0",
    "@heroicons/react": "^1.0.6",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.2",
    "@tailwindcss/line-clamp": "^0.4.0",
    "@tailwindcss/typography": "^0.5.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.3.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.0.1",
    "typescript": "^4.6.4",
    "vite": "^3.0.6",
    "vite-plugin-next-react-router": "^0.6.2"
  }
}

```

## What is happening:
- when Outlet is missing in imports, the pages are blank and the error in Console is
`Uncaught ReferenceError: Outlet is not defined`
- this happens every time I start dev server (routes are generated at every app start)
- this does not affect hot reload

## Expected behavior:
- every dependency used by code generator should be propelry imported
- user should not manually edit this file

## Current solution:
- manually add dependency

**Comment by stereoplegic** [comment]
I can confirm this bug; however, I was able to work around it by adding an Outlet in any index page with siblings (folders or page files*). Look at the in the `examples/react` folder.

*`pages/index.[jsx/tsx]` is an exception if you use `pages/_layout.[jsx/tsx]` like the example

**Comment by pawelkrystkiewicz** [comment]
@stereoplegic sound great doesn't work
![Zrzut ekranu 2022-09-25 o 19 02 43](https://user-images.githubusercontent.com/28536511/192155934-a5c7d42c-8bc1-437b-a1fc-8a855c2fd4b0.png)
The `Outlet` in `routes.tsx` will be yelling undefined

**Comment by stereoplegic** [comment]
I ended up just putting an Outlet as the innermost child in `pages/_layout.jsx` (manually importing it from RR in that file). That gets imported as GlobalLayout in `generated/routes.jsx` when vite-plugin-next-react-router builds. It then doesn't need to add an Outlet in the generated file, and I haven't needed any other Outlets in my pages.

**Comment by zoubingwu** [comment]
had a major rewrite in 0.7,0, this should be fixes
